sudo: required
services:
    - docker

before_install:
    - docker build -t ash7c/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ash7c/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-326530706971"
    bucket_path: "docker"

    on:
        branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY